# Codemagic CI/CD Configuration for BVI Park & Ride
# Documentation: https://docs.codemagic.io/yaml/yaml-getting-started/

workflows:
  # ==================== RIDER APP ====================
  rider-app-ios:
    name: Rider App iOS
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.bvi.parkandride.rider
      vars:
        MAPBOX_SECRET_TOKEN: $MAPBOX_SECRET_TOKEN
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      # Set up Mapbox SDK download token
      - name: Configure Mapbox
        script: |
          echo "machine api.mapbox.com" >> ~/.netrc
          echo "login mapbox" >> ~/.netrc
          echo "password ${MAPBOX_SECRET_TOKEN}" >> ~/.netrc
          chmod 600 ~/.netrc
      - name: Get Flutter packages
        script: |
          cd apps/rider_app
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd apps/rider_app/ios
          pod install
      - name: Build iOS
        script: |
          cd apps/rider_app
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - apps/rider_app/build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration

  rider-app-android:
    name: Rider App Android
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      android_signing:
        - bvi_keystore
      vars:
        MAPBOX_ACCESS_TOKEN: pk.eyJ1IjoiZGV6ZXRpbmd6IiwiYSI6ImNtaW42anV4azIwM3ozY3B3eGpxdWlxenYifQ.Y5YI-07V6nwBUCPxF7qH3w
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          cd apps/rider_app
          flutter pub get
      - name: Build Android APK
        script: |
          cd apps/rider_app
          flutter build apk --release
      - name: Build Android App Bundle
        script: |
          cd apps/rider_app
          flutter build appbundle --release
    artifacts:
      - apps/rider_app/build/app/outputs/**/*.apk
      - apps/rider_app/build/app/outputs/**/*.aab
    publishing:
      google_play:
        credentials: $GPLAY_SERVICE_ACCOUNT_CREDENTIALS
        track: internal

  # ==================== DRIVER APP ====================
  driver-app-ios:
    name: Driver App iOS
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.bvi.parkandride.driver
      vars:
        MAPBOX_SECRET_TOKEN: $MAPBOX_SECRET_TOKEN
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Configure Mapbox
        script: |
          echo "machine api.mapbox.com" >> ~/.netrc
          echo "login mapbox" >> ~/.netrc
          echo "password ${MAPBOX_SECRET_TOKEN}" >> ~/.netrc
          chmod 600 ~/.netrc
      - name: Get Flutter packages
        script: |
          cd apps/driver_app
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd apps/driver_app/ios
          pod install
      - name: Build iOS
        script: |
          cd apps/driver_app
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - apps/driver_app/build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration

  driver-app-android:
    name: Driver App Android
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      android_signing:
        - bvi_keystore
      vars:
        MAPBOX_ACCESS_TOKEN: pk.eyJ1IjoiZGV6ZXRpbmd6IiwiYSI6ImNtaW42anV4azIwM3ozY3B3eGpxdWlxenYifQ.Y5YI-07V6nwBUCPxF7qH3w
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          cd apps/driver_app
          flutter pub get
      - name: Build Android APK
        script: |
          cd apps/driver_app
          flutter build apk --release
      - name: Build Android App Bundle
        script: |
          cd apps/driver_app
          flutter build appbundle --release
    artifacts:
      - apps/driver_app/build/app/outputs/**/*.apk
      - apps/driver_app/build/app/outputs/**/*.aab
    publishing:
      google_play:
        credentials: $GPLAY_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
