name: bvi_park_and_ride

packages:
  - apps/*

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  # Clean all packages
  clean:
    run: melos exec -- flutter clean
    description: Clean all packages

  # Get dependencies for all packages
  get:
    run: melos exec -- flutter pub get
    description: Get dependencies for all packages

  # Run driver app
  run:driver:
    run: cd apps/driver_app && flutter run
    description: Run the driver app

  # Run rider app
  run:rider:
    run: cd apps/rider_app && flutter run
    description: Run the rider app

  # Build debug APKs
  build:debug:
    run: melos exec -- flutter build apk --debug
    description: Build debug APKs for all apps

  # Build release APKs
  build:release:
    run: melos exec -- flutter build apk --release
    description: Build release APKs for all apps

  # Build driver app
  build:driver:
    run: cd apps/driver_app && flutter build apk --release
    description: Build driver app release APK

  # Build rider app
  build:rider:
    run: cd apps/rider_app && flutter build apk --release
    description: Build rider app release APK

  # Analyze all packages
  analyze:
    run: melos exec -- flutter analyze
    description: Analyze all packages

  # Run tests
  test:
    run: melos exec -- flutter test
    description: Run tests for all packages
